# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\NSCC\PROG1700Logic and Programming I\Prog1700_SourceCode\w0437076-KarsonA\Final Project\FlagDesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CountryList = QtWidgets.QListWidget(self.centralwidget)
        self.CountryList.setGeometry(QtCore.QRect(39, 69, 261, 451))
        self.CountryList.setObjectName("CountryList")
        self.ChooseACountrylabel = QtWidgets.QLabel(self.centralwidget)
        self.ChooseACountrylabel.setGeometry(QtCore.QRect(46, 22, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ChooseACountrylabel.setFont(font)
        self.ChooseACountrylabel.setTextFormat(QtCore.Qt.AutoText)
        self.ChooseACountrylabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ChooseACountrylabel.setObjectName("ChooseACountrylabel")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(320, 49, 431, 491))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.Populationlabel = QtWidgets.QLabel(self.mainFrame)
        self.Populationlabel.setGeometry(QtCore.QRect(10, 190, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Populationlabel.setFont(font)
        self.Populationlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Populationlabel.setObjectName("Populationlabel")
        self.UPButtom = QtWidgets.QPushButton(self.mainFrame)
        self.UPButtom.setGeometry(QtCore.QRect(170, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UPButtom.setFont(font)
        self.UPButtom.setObjectName("UPButtom")
        self.frame_2 = QtWidgets.QFrame(self.mainFrame)
        self.frame_2.setGeometry(QtCore.QRect(40, 320, 321, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.PopulationDensitylabel = QtWidgets.QLabel(self.frame_2)
        self.PopulationDensitylabel.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PopulationDensitylabel.setFont(font)
        self.PopulationDensitylabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PopulationDensitylabel.setObjectName("PopulationDensitylabel")
        self.RBMiles = QtWidgets.QRadioButton(self.frame_2)
        self.RBMiles.setGeometry(QtCore.QRect(0, 30, 121, 31))
        self.RBMiles.setObjectName("RBMiles")
        self.RBKM = QtWidgets.QRadioButton(self.frame_2)
        self.RBKM.setGeometry(QtCore.QRect(0, 50, 131, 41))
        self.RBKM.setObjectName("RBKM")
        self.PopulationDensity = QtWidgets.QLabel(self.frame_2)
        self.PopulationDensity.setGeometry(QtCore.QRect(220, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PopulationDensity.setFont(font)
        self.PopulationDensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PopulationDensity.setObjectName("PopulationDensity")
        self.TotalArealabel = QtWidgets.QLabel(self.mainFrame)
        self.TotalArealabel.setGeometry(QtCore.QRect(40, 280, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TotalArealabel.setFont(font)
        self.TotalArealabel.setObjectName("TotalArealabel")
        self.DDMilesKM = QtWidgets.QComboBox(self.mainFrame)
        self.DDMilesKM.setGeometry(QtCore.QRect(120, 280, 69, 31))
        self.DDMilesKM.setObjectName("DDMilesKM")
        self.DDMilesKM.addItem("")
        self.DDMilesKM.addItem("")
        self.PercentWPlabel = QtWidgets.QLabel(self.mainFrame)
        self.PercentWPlabel.setGeometry(QtCore.QRect(40, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PercentWPlabel.setFont(font)
        self.PercentWPlabel.setObjectName("PercentWPlabel")
        self.FlagImage = QtWidgets.QLabel(self.mainFrame)
        self.FlagImage.setGeometry(QtCore.QRect(10, 30, 421, 151))
        self.FlagImage.setText("")
        self.FlagImage.setPixmap(QtGui.QPixmap("Basic_CountriesOfTheWorld/Flags/Afghanistan.png"))
        self.FlagImage.setAlignment(QtCore.Qt.AlignCenter)
        self.FlagImage.setObjectName("FlagImage")
        self.TotalAreaNr = QtWidgets.QLabel(self.mainFrame)
        self.TotalAreaNr.setGeometry(QtCore.QRect(260, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TotalAreaNr.setFont(font)
        self.TotalAreaNr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalAreaNr.setObjectName("TotalAreaNr")
        self.PercentWP = QtWidgets.QLabel(self.mainFrame)
        self.PercentWP.setGeometry(QtCore.QRect(280, 430, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PercentWP.setFont(font)
        self.PercentWP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PercentWP.setObjectName("PercentWP")
        self.FlagName = QtWidgets.QLabel(self.mainFrame)
        self.FlagName.setGeometry(QtCore.QRect(0, 0, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FlagName.setFont(font)
        self.FlagName.setObjectName("FlagName")
        self.Popamount = QtWidgets.QLineEdit(self.mainFrame)
        self.Popamount.setGeometry(QtCore.QRect(110, 190, 281, 21))
        self.Popamount.setObjectName("Popamount")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Countries = QtWidgets.QAction(MainWindow)
        self.actionLoad_Countries.setObjectName("actionLoad_Countries")
        self.actionSave_To_File = QtWidgets.QAction(MainWindow)
        self.actionSave_To_File.setEnabled(False)
        self.actionSave_To_File.setObjectName("actionSave_To_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoad_Countries)
        self.menuFile.addAction(self.actionSave_To_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ChooseACountrylabel.setText(_translate("MainWindow", "Choose a country from the List:"))
        self.Populationlabel.setText(_translate("MainWindow", "Population:"))
        self.UPButtom.setText(_translate("MainWindow", "Update Population"))
        self.PopulationDensitylabel.setText(_translate("MainWindow", "Population Density:"))
        self.RBMiles.setText(_translate("MainWindow", "Per Square Mile"))
        self.RBKM.setText(_translate("MainWindow", "Per Square KM"))
        self.PopulationDensity.setText(_translate("MainWindow", "PopDensity"))
        self.TotalArealabel.setText(_translate("MainWindow", "Total Area in"))
        self.DDMilesKM.setItemText(0, _translate("MainWindow", "Sq.Miles"))
        self.DDMilesKM.setItemText(1, _translate("MainWindow", "Sq.KM"))
        self.PercentWPlabel.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.TotalAreaNr.setText(_translate("MainWindow", "Total Area Nr."))
        self.PercentWP.setText(_translate("MainWindow", "PercentageWorldPOP"))
        self.FlagName.setText(_translate("MainWindow", "FlagName"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Countries.setText(_translate("MainWindow", "Load Countries"))
        self.actionSave_To_File.setText(_translate("MainWindow", "Save To File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
